### ISSUE TITLE
Same comment is repeated in module.ts in L21-55

### ISSUE THREAD

**Issue by tmlmt** [raphaelbernhart/nuxt-cookieconsent#3]

**Comment by raphaelbernhart** [comment]
@tmlmt Thanks for the support :)

I'll come back to this issue when I am finishing the module (npm package, CI/CD, code refinement)

**Comment by raphaelbernhart** [comment]
Fixed with https://github.com/raphaelbernhart/nuxt-cookieconsent/pull/5
